ALTER TABLE ACAOCONJDEBASES_ACOES
ADD CONSTRAINT FK_ACAOCONJDEBASES_ACOES_1
FOREIGN KEY (PARENTCLASS,PARENTID)
REFERENCES ACAOCONJUNTODEBASES(CLASS,ID)
ON DELETE CASCADE;

ALTER TABLE ACAOCONJDEBASES_ACOES
ADD CONSTRAINT FK_ACAOCONJDEBASES_ACOES_2
FOREIGN KEY (CHILDCLASS,CHILDID)
REFERENCES ACAOCONFIGURARBASEDEDADOS(CLASS,ID)
ON DELETE CASCADE;

ALTER TABLE ACAOCONJDEBASES_CATALOGOS
ADD CONSTRAINT FK_ACAOCONJDEBASES_CATALOGOS_1
FOREIGN KEY (PARENTCLASS,PARENTID)
REFERENCES ACAOCONJUNTODEBASES(CLASS,ID)
ON DELETE CASCADE;

ALTER TABLE ACAOCONJDEBASES_CATALOGOS
ADD CONSTRAINT FK_ACAOCONJDEBASES_CATALOGOS_2
FOREIGN KEY (CHILDCLASS,CHILDID)
REFERENCES ACAOCATALOGODEBASES(CLASS,ID)
ON DELETE CASCADE;

ALTER TABLE BARRAFERRAMENTA_ACOES
ADD CONSTRAINT FK_BARRAFERRAMENTA_ACOES_1
FOREIGN KEY (PARENTCLASS,PARENTID)
REFERENCES BARRAFERRAMENTA(CLASS,ID)
ON DELETE CASCADE;

ALTER TABLE BARRAFERRAMENTA_ACOES
ADD CONSTRAINT FK_BARRAFERRAMENTA_ACOES_2
FOREIGN KEY (CHILDCLASS,CHILDID)
REFERENCES ACAOEXECUTAR(CLASS,ID)
ON DELETE CASCADE;